version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
      - '4466:4466'
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-23-21-156-171.compute-1.amazonaws.com
            database: d7qciuchcar71j
            user: lipnyuxewxfuah
            password: 42b6170d134bd5e82b24d93aa9e05cfdd1774500469d9c95e8f9619734c55ef4
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true
